name: docker-image-push-to-dockerhub-pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main'
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use latest Ubuntu

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Java version 21
          distribution: 'temurin'  # Temurin distribution

      # Build project with Maven
      - name: Build with Maven
        run: mvn clean install  # Maven build

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker password

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Current directory
          file: ./Dockerfile  # Dockerfile path
          push: true  # Push image
          tags: 9494624217/welcome-app:latest  # Latest tag
          #tags: 9494624217/welcome-app:${{ github.sha }}  # Commit tag (optional)
